### PR TITLE
Debug release

### PR DESCRIPTION
**Pull request by dlyr**

### CODE REVIEW

**Comment by dlyr** [comment]
It do not pass the tests ... my modification change the value of default directory.
If you could please have a look, I could change the code but i'm quite new to lisp, and not sure to catch exactly how it should behave.

**Comment by atilaneves** [comment]
I'm guessing it's the changes to `cmake-ide--get-build-dir`

**Comment by dlyr** [comment]
Seems like I manage to pass the tests ...  `cmake-ide--get-build-dir` as two different behaviors : 
if there is no CMakeLists.txt, then it look if the `cmake-build-dir--var` is set and use it
else if a CMakeLists.txt is found, it build a "project key" from the directory of the CMakeLists.txt and the ` cmake-ide-cmake-opts` var (something I added, may be in conflict with another pull request ... I will merge if needed)
then the build-dir is retrieve (or stored if not present for that key) from a hash map (this allows to have also temp build dir that stay consistent during a emacs session). 
It allows to open multiple cmake project within a session and to have different build dirs for debug release.

I add the following to my .emacs to allow quick debug/release build : 

```lisp
(defun compile-in-release ()
  "Set compil flag and run."
  (interactive)
  (progn
    (let ((buffer (compilation-find-buffer)))
      (if (get-buffer-process buffer)
	  (interrupt-process (get-buffer-process buffer))
	))
    (setq cmake-ide-cmake-opts "-DCMAKE_BUILD_TYPE=Release")
    (cmake-ide-run-cmake)
    (cmake-ide-compile)
    )
  )

(defun compile-in-debug ()
  "Set compil flag and run."
  (interactive)
  (progn
    (let ((buffer (compilation-find-buffer)))
      (if (get-buffer-process buffer)
	  (interrupt-process (get-buffer-process buffer))
	))
    (setq cmake-ide-cmake-opts "-DCMAKE_BUILD_TYPE=Debug")
    (cmake-ide-run-cmake)
    (cmake-ide-compile)
    )
  )
```

**Comment by dlyr** [comment]
I'm coming back from QtCreator which handles easily multiple build dir for the same project with different cmake configuation, and my wish is to obtain the same with `cmake-ide.`
Maybe it could be something like 
if `cmake-ide-build-dir` is set use it (without further computation)
if not use the `cmake-ide--get-build-dir` to get an build dir that depends on `cmake-ide--locate-cmakelists` and `cmake-ide--cmake-opts,` store it in the hashtable, but do not set `cmake-ide-build-dir`
Hence each call to `cmake-ide--get-build-dir` has the same behavior (because if `cmake-ide-build-dir` is set during the first call, next calls will use its value regardless of changing directory or `cmake-opts,` unless set in `.dir-locals.el)`
Another option is I could define on my side an emacs function that use `cmake-ide-build-dir` set in .dir-locals.el and modify it `depending` on the `cmake-opts,` independently from `cmake-ide`

**Pull request merged**
